# MediaWiki with MariaDB
#
# Setup a custom entry in /etc/hosts for localhost (e.g. mediawiki)
# then access via "http://mediawiki"
#
# Edit the .env file with your PUBLIC_HOSTNAME 
#

services:
  mediawiki:
    build:
      context: .
      dockerfile: docker/Mediawiki.Dockerfile
      args:
        PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
        WIKI_INTERNAL_HOSTNAME: mediawiki
        WIKI_NAME: ${WIKI_NAME}
        WIKI_ADMIN_PASSWORD: ${WIKI_ADMIN_PASSWORD}
        PRODUCTION_SSH_HOST: ${PRODUCTION_SSH_HOST}
        DATA_IMPORT_USER: ${DATA_IMPORT_USER}
        DB_SERVER: ${DB_SERVER}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        EMAIL_CONTACT: ${EMAIL_CONTACT}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASS: ${SMTP_PASS}
        GTM_ID: ${GTM_ID}
    restart: always
    # TODO: start here
    # command:
      # See also CMD, ENTRYPOINT
    depends_on:
      - wiki-database
        #    ports:
        #      - 8080:80
    volumes:
      - mediawiki_html:/var/www/html
        #      - ./mediawiki/webroot/extensions:/var/www/html/extensions
#      - ./mediawiki/webroot/images:/var/www/html/images
      - ./mediawiki/defaults/LocalSettings.default:/var/www/html/defaults/LocalSettings.default
      - ./mediawiki/init.sh:/init.sh
      - ./cache:/app/cache
    environment:
      PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
      WIKI_INTERNAL_HOSTNAME: mediawiki
      WIKI_NAME: ${WIKI_NAME}
      WIKI_ADMIN_PASSWORD: ${WIKI_ADMIN_PASSWORD}
      PRODUCTION_SSH_HOST: ${PRODUCTION_SSH_HOST}
      DATA_IMPORT_USER: ${DATA_IMPORT_USER}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      EMAIL_CONTACT: ${EMAIL_CONTACT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      GTM_ID: ${GTM_ID}
      PHP_MEMORY_LIMIT: 1024M
    expose:
      - "9000"

  wiki-database:
    image: mariadb:11.6.2
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    image: base

  q_serve:
    build:
      context: .
      dockerfile: docker/QServe.Dockerfile
    depends_on:
      - base
    expose:
      - "8090"

  zip_worker:
    build:
      context: .
      dockerfile: docker/Worker.Dockerfile
    command: >
      python
      -u -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m mwlib.core.nslave
      --cachedir /app/cache
      --host q_serve
      --port 8090
      --numprocs 2
      -c makezip
      # nslave 
      # --cachedir /app/cache 
      # --host q_serve 
      # --port 8090
      # --numprocs 2 
      # -c makezip
    ports:
      - "5678:5678"
    environment:
      DEBUGPY: 0
      GEVENT_SUPPORT: True
    depends_on:
      - base
      - q_serve
    volumes:
      - ./cache:/app/cache

  job_dispatcher:
    build:
      context: .
      dockerfile: docker/JobDispatcher.Dockerfile
    depends_on:
      - base
      - q_serve
    environment:
      DEBUGPY: 0
      GEVENT_SUPPORT: True
    command: >
      python
      -u -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5680 -m mwlib.core.nserve q_serve:8090
    expose:
      - "8899"
    ports:
      - "5680:5680"

  render_worker:
    build:
      context: .
      dockerfile: docker/Worker.Dockerfile
    depends_on:
      - base
      - q_serve
    command: >
      python
      -u -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5679 -m mwlib.core.nslave
      --cachedir /app/cache
      --host q_serve
      --port 8090
      --numprocs 2
      --url http://render_worker:9123/cache
      -c render
      # nslave
      # --cachedir /app/cache
      # --host q_serve
      # --port 8090
      # --numprocs 2
      # --url http://render_worker:9123/cache
      # -c render
    ports:
      - "5679:5679"
    environment:
      DEBUGPY: 0
      GEVENT_SUPPORT: True
    volumes:
      - ./cache:/app/cache

  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    restart: unless-stopped
    depends_on:
      - mediawiki
    networks:
      default:
        aliases:
          - mediawiki
    volumes:
      - mediawiki_html:/var/www/html
      - ./prerender:/var/www/html/prerender
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot:/var/lib/letsencrypt
      - ./certs:/etc/letsencrypt/
      - ./cache:/app/cache
    expose:  
      - "8080:80"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt/
      - ./certbot:/var/lib/letsencrypt
#    entrypoint: ["sleep", "infinity"]  # Keeps the container running
    entrypoint: >
      /bin/sh -c 
      "trap exit TERM; 
      while :; do
      certbot renew --webroot -w /var/lib/letsencrypt --quiet;
      sleep 12h &
      wait $${!};
      done"


volumes:
  db:
  mediawiki_html:

