# MediaWiki with MariaDB

services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8000:80
    links:
      - database
    volumes:
      - ./mediawiki/images:/var/www/html/images
      - ./mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./mediawiki/extensions/Collection:/var/www/html/extensions/Collection
      - ./cache:/app/cache
    extra_hosts:
      - "pediapress.com:host-gateway"
      - "asset_server:host-gateway"

  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  reverse_proxy:
    image: nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  images:
  db:
  mediawiki:
