# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: "3"
services:
  mediawiki:
    image: mediawiki
    restart: always
    links:
      - database
    ports:
      - 80:80
    expose:
      - "80"
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./extensions/Collection:/var/www/html/extensions/Collection

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    image: mw-base

  q_serve:
    build:
      context: ..
      dockerfile: docker/QServe.Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - base
    expose:
      - "8090"

  n_serve:
    build:
      context: ..
      dockerfile: docker/NServe.Dockerfile
    ports:
      - "8899:8899"
    depends_on:
      - base
      - q_serve
    expose:
      - "8899"

  n_slave_zip:
    build:
      context: ..
      dockerfile: docker/NSlaveZip.Dockerfile
    depends_on:
      - base
      - q_serve
    volumes:
      - ./cache:/app/cache
      
  n_slave_render:
    build:
      context: ..
      dockerfile: docker/NSlave.Dockerfile
    depends_on:
      - base
      - q_serve
    ports:
      - "9123:9123"
    expose: 
      - "9123"
    volumes:
      - ./cache:/app/cache

  postman:
    build:
      context: ..
      dockerfile: docker/Postman.Dockerfile
    depends_on:
      - base
      - q_serve


volumes:
  images:
  db:
