version: '3'
services:
  nserve:
    image: gcr.io/ppcloud-224610/mwlib:latest
    container_name: nserve
    ports:
      - "8899:8899"
    command: nserve qserve:14311
    depends_on:
      - qserve
  qserve:
    image: gcr.io/ppcloud-224610/mwlib:latest
    container_name: qserve
    command: mw-qserve
  nslave-render:
    image: gcr.io/ppcloud-224610/mwlib:latest
    container_name: nslave-render
    command: >
      nslave
      --cachedir /cache
      --host qserve
      --url https://newtools.pediapress.com/cache
      --numprocs 5
      -s makezip
    volumes:
      - "/mnt/disks/data/docker-compose-data/cache:/cache"
      # - "/tmp/cache:/cache"
    depends_on:
      - qserve
  nslave-zip:
    image: gcr.io/ppcloud-224610/mwlib:latest
    container_name: nslave-zip
    command: >
      nslave
      --cachedir /cache
      --host qserve
      --url https://newtools.pediapress.com/cache
      --numprocs 10
      -c makezip
    volumes:
      - "/mnt/disks/data/docker-compose-data/cache:/cache"
      # - "/tmp/cache:/cache"
    depends_on:
      - qserve
