# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./extensions/Collection:/var/www/html/extensions/Collection
  
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    image: mw-base

  n_serve:
    build:
      context: ..
      dockerfile: docker/NServe.Dockerfile
    ports:
      - "8899:8899"
    depends_on:
      - base
      - q_serve

  n_slave_render:
    build:
      context: ..
      dockerfile: docker/NSlave.Dockerfile
    ports:
      - "9125:8898"
    depends_on:
      - base
      - q_serve

  n_slave_zip:
    build:
      context: ..
      dockerfile: docker/NSlaveZip.Dockerfile
    ports:
      - "9126:8898"
    depends_on:
      - base
      - q_serve

  q_serve:
    build:
      context: ..
      dockerfile: docker/QServe.Dockerfile
    ports:
      - "14311:8080"
    depends_on:
      - base
      
volumes:
  images:
  db:
